name: Continuous Deployment
on:
  push:
    branches:
      - master
      -
    jobs:
      deploy:
        name: Deploy
        runs-on: ubuntu-latest

      env:
        SOURCE_DIR: "./"
        AWS_REGION: "us-east-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}

      steps:
        - uses: actions/checkout@v1

        - name: Deploy www
          uses: jakejarvis/s3-sync-action@v0.5.0
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.WWW_AWS_S3_BUCKET }}

        - name: Deploy regular
          uses: jakejarvis/s3-sync-action@v0.5.0
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.REGULAR_AWS_S3_BUCKET }}
